name: Build and Deploy to Docker Hub and Render

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with multiple tags
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/miapp:latest \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/miapp:${{ env.SHA_SHORT }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/miapp:${{ env.DATE }} .

      - name: Push Docker image (all tags)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/miapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/miapp:${{ env.SHA_SHORT }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/miapp:${{ env.DATE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
